name: dart2d
description: Dart2d WebRTC Game
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0'
  di: '>=3.3.4 <4.0.0'
  convert: any
  logging: any
dev_dependencies:
  test: '>=0.12.9'
  mockito: any
transformers:
 - di