name: dart2d
description: Dart2d WebRTC Game
environment:
  sdk: '>=3.3.0'
dependencies:
  web: '>=1.1.1'
  convert: 3.1.2
  logging: any
  get_it: any
  injectable: any
  protobuf: 3.1.0
  clock: any
  uuid: ^4.4.2
dev_dependencies:
  test: '>=0.12.9'
  mockito: any
  injectable_generator: any
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.3
  matcher: any
platforms:
  web: